kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-config
data:
  ldap.toml: >
    [[servers]]
    host = "ldap.ldap.svc"
    port = 389
    use_ssl = false
    start_tls = false
    ssl_skip_verify = false
    bind_dn = "cn=admin,dc=example,dc=com"
    bind_password = 'admin'
    search_filter = "(uid=%s)"
    search_base_dns = ["ou=Users,dc=example,dc=com"]
    group_search_base_dns = ["ou=Groups,dc=example,dc=org"]


    [servers.attributes]
    username = "uid"
    surname = "sn"
    email = "mail"
    name = "uid"
    
    # Optional, otherwise all members are viewrs, possible value Viewer, Admin
    [[servers.group_mappings]]
    group_dn = "*"
    org_role = "Editor"
